### ISSUE TITLE
Assertion errors

### ISSUE THREAD

**Issue by ettorep** [vintagedave/firemonkey-container#7] opened 2016-02-10 16:29 UTC
Windows 7
Delphi XE5 32bit

Two assertion errors.

To reproduce add FMXontainer to vcl form, add new fmx form with a button on it.
 for the onclick even add this code:

 InputBox('xx','xx','xx'); 

and when you run it and click on the button, I get the assertion errors.

If I comment out the 2 lines then the input will show up but will be frozen (not Responding) and have to terminate the program.

**Comment by vintagedave** [comment] 2016-04-14 18:28
This is fixed in the latest revision. Caused by the same thing as #8.

**Closed by vintagedave** 2016-04-14 18:28 UTC
